#define EOK               0
#define EFAILED          -1
#define EBADPARM         -2
#define EFULL            -3
#define EEMPTY           -4
#define ENOMEMORY        -5
#define EEXISTS          -6
#define ENOTEXIST        -7
#define ENOTALLOWED      -8
#define EUNSUPPORTED     -9
